name: Code Coverage
on:
  push:
    branches: [ main ]

jobs:
  code-coverage:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Java
        uses: actions/setup-java@v2
        with:
          java-version: '21'

      - name: Build with Gradle
        run: ./gradlew build  

      - name: Run Tests and Collect Code Coverage
        run: ./gradlew test  

      - name: Upload Code Coverage Report
        uses: actions/upload-artifact@v2
        with:
          name: code-coverage-report
          path: build/reports/jacoco/test/html  

      - name: Comment on PR with Code Coverage
        uses: actions/github-script@0.10.0
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const fs = require('fs');
            const coverageReport = fs.readFileSync('build/reports/jacoco/test/html/index.html', 'utf8');
            const comment = '### Code Coverage Report\n' + coverageReport;
            await github.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: comment,
            });
