name: Java CI
on:
  push:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v2

    - name: Set up Java
      uses: actions/setup-java@v2
      with:
        java-version: '21'
        distribution: 'adopt'   
    - name: Checkout Code
      uses: actions/checkout@v2
  
    - name: Set up Java
      uses: actions/setup-java@v2
      with:
        java-version: '21'
    
    - name: Compile
      run: javac -d . -sourcepath src src/com/mytaskmanager/*.java
    
    - name: Run Tests
      run: java com.mytaskmanager.MainApp
    
