name: Java CI
on:
  push:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v2
  
    - name: Set up Java
      uses: actions/setup-java@v2
      with:
        java-version: '21'
        distribution: 'adopt'
    
    - name: Compile
      run: |
       javac my-task-manager-app/src/main/java/com/mytaskmanager/MainApp.java
       java MainApp.java
    
