name: Code Linting
on:
  push:
    branches: [ main ]

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Java
        uses: actions/setup-java@v2
        with:
          java-version: '21'

      - name: Clear npm Cache
        run: npm cache clean --force

      - name: Install JavaScript Dependencies
        run: npm install /home/runner/work/githubactions/githubactions/package.json

      - name: JavaScript Linting
        run: npm run lint  # Adjust to your specific linting command
