name: Code Linting

on:
  push:
    branches: [ main ] 

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set up Java
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'

      - name: Build project with Maven
        run: mvn -B package --file my-task-manager-app/pom.xml
        working-directory: my-task-manager-app

      - name: Checkstyle
        run: mvn checkstyle:check
        working-directory: my-task-manager-app
