name: XmlLint
on:
  push:
    branches: branch-name
jobs:
  xml-linters:
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@master
    - name: Download schema
      run: wget https://apps.nextcloud.com/schema/apps/info.xsd
    - name: Lint info.xml
      uses: ChristophWusrt/xmllint-action@v1
      with:
        xml-file: my-task-manager-app/pom.xml
        xml-schema-file: ./info.xsd
